################################################################################
##------------------------------------------------------------------------------
## Caribbean CVA
## Script 2. QA checks and figures
##
## Purpose:
## - Read outputs from Script 1
## - Run QA checks on baseline reproduction, bootstrap uncertainty, and
##   leave-one-out completeness
## - Write QA tables and logs
## - Generate manuscript-ready figures
##
## Workflow
##
## Step 1. Read analysis outputs from Script 1
## Step 2. QA check baseline reproduction
## Step 3. QA check bootstrap completeness and probability sums
## Step 4. QA check leave-one-out completeness
## Step 5. Flag analytical edge cases
## Step 6. Make figures
##
## Notes:
## - This script should not rerun bootstrap or leave-one-out analyses
## - It should only use outputs generated by Script 1
## - Figures should be made from summary tables, not raw workbooks

##------------------------------------------------------------------------------
## User setup

rm(list = ls()); gc()

library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(ggplot2)
library(forcats)

##------------------------------------------------------------------------------
## User setup - directories

proj_dir <- "."
in_dir   <- file.path(proj_dir, "outputs", "final-scores-compiled")
out_dir  <- file.path(in_dir, "uncertainty-loo")

intermediate_dir <- file.path(out_dir, "intermediate")
final_dir        <- file.path(out_dir, "final-tables")
qa_dir           <- file.path(out_dir, "qa")
fig_dir          <- file.path(out_dir, "figures")

dir.create(qa_dir,  recursive = TRUE, showWarnings = FALSE)
dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)

##------------------------------------------------------------------------------
## User setup - input files from Script 1

f_precheck_log     <- file.path(intermediate_dir,
                                "02_preanalysis_check_log.csv")

f_base_comp_repro  <- file.path(intermediate_dir,
                                "03_baseline_reproduced_component_scores.csv")

f_base_vuln_repro  <- file.path(intermediate_dir,
                                "03_baseline_reproduced_vulnerability_scores.csv")

f_boot_stock <- file.path(final_dir,
                          "table_bootstrap_uncertainty_stock.csv")

f_boot_sens  <- file.path(final_dir,
                          "table_bootstrap_uncertainty_sensitivity_component.csv")

f_loo_sens_long <- file.path(final_dir,
                             "table_leave_one_out_sensitivity_long.csv")

f_loo_exp_long  <- file.path(final_dir,
                             "table_leave_one_out_exposure_long.csv")

f_loo_sens_sum  <- file.path(final_dir,
                             "table_leave_one_out_sensitivity_summary.csv")

f_loo_exp_sum   <- file.path(final_dir,
                             "table_leave_one_out_exposure_summary.csv")

f_plot_exp <- file.path(final_dir,
                        "table_exposure_factor_scores_for_plot.csv")

f_plot_sens <- file.path(final_dir,
                         "table_sensitivity_attribute_scores_for_plot.csv")

## Official baseline file for comparison
f_vuln <- file.path(in_dir,
                    "final-attribute-scores",
                    "overall_vulnerability_scores_uscar.csv")

##------------------------------------------------------------------------------
## User setup - QA output files

f_qa_baseline <- file.path(qa_dir,
                           "table_qa_baseline_match.csv")

f_qa_boot     <- file.path(qa_dir,
                           "table_qa_bootstrap_checks.csv")

f_qa_loo      <- file.path(qa_dir,
                           "table_qa_leave_one_out_checks.csv")

f_qa_edge     <- file.path(qa_dir,
                           "table_qa_edge_cases.csv")

##------------------------------------------------------------------------------
## User setup - figure output files

f_fig_exp_box <- file.path(fig_dir,
                           "Fig_exposure_factor_score_distributions.png")

f_fig_exp_loo <- file.path(fig_dir,
                           "Fig_exposure_leave_one_out_barplot.png")

f_fig_sens_box <- file.path(fig_dir,
                            "Fig_sensitivity_attribute_score_distributions.png")

f_fig_sens_loo <- file.path(fig_dir,
                            "Fig_sensitivity_leave_one_out_barplot.png")

f_fig_boot_stack <- file.path(fig_dir,
                              "Fig_vulnerability_uncertainty_stacked_barplot.png")

##------------------------------------------------------------------------------
## Step 1 - Read analysis outputs from Script 1

precheck_log    <- read_csv(f_precheck_log,    show_col_types = FALSE)
base_comp_repro <- read_csv(f_base_comp_repro, show_col_types = FALSE)
base_vuln_repro <- read_csv(f_base_vuln_repro, show_col_types = FALSE)

boot_stock      <- read_csv(f_boot_stock,      show_col_types = FALSE)
boot_sens       <- read_csv(f_boot_sens,       show_col_types = FALSE)

loo_sens_long   <- read_csv(f_loo_sens_long,   show_col_types = FALSE)
loo_exp_long    <- read_csv(f_loo_exp_long,    show_col_types = FALSE)

loo_sens_sum    <- read_csv(f_loo_sens_sum,    show_col_types = FALSE)
loo_exp_sum     <- read_csv(f_loo_exp_sum,     show_col_types = FALSE)

plot_exp_scores <- read_csv(f_plot_exp,        show_col_types = FALSE)
plot_sens_scores <- read_csv(f_plot_sens,      show_col_types = FALSE)

vuln_official   <- read_csv(f_vuln,            show_col_types = FALSE)

##------------------------------------------------------------------------------
## Step 2 - QA check baseline reproduction
##
## Workflow:
## - Join official baseline table to reproduced baseline table
## - Confirm numeric scores and ranks match exactly
## - Confirm no missing or extra stocks

qa_baseline <- vuln_official %>%
  select(stock_name,
         exposure_score_numeric, exposure_rank,
         sensitivity_score_numeric, sensitivity_rank,
         vulnerability_score_numeric, vulnerability_rank) %>%
  left_join(base_vuln_repro, by = "stock_name") %>%
  mutate(
    exp_num_match  = exposure_score_numeric == exposure_score_numeric_repro,
    exp_rank_match = exposure_rank == exposure_rank_repro,
    sens_num_match = sensitivity_score_numeric == sensitivity_score_numeric_repro,
    sens_rank_match = sensitivity_rank == sensitivity_rank_repro,
    vuln_num_match = vulnerability_score_numeric == vulnerability_score_numeric_repro,
    vuln_rank_match = vulnerability_rank == vulnerability_rank_repro,
    all_match = exp_num_match & exp_rank_match &
      sens_num_match & sens_rank_match &
      vuln_num_match & vuln_rank_match
  )

write_csv(qa_baseline, f_qa_baseline)

if(any(!qa_baseline$all_match, na.rm = TRUE)) {
  stop("Baseline QA failed. Review table_qa_baseline_match.csv")
}

##------------------------------------------------------------------------------
## Step 3 - QA check bootstrap completeness and probability sums
##
## Workflow:
## - Confirm every stock has n_boot = 10000
## - Confirm probabilities sum to 1 within tolerance
## - Confirm modal rank is legal
## - Confirm certainty value corresponds to probability of baseline rank

qa_boot <- boot_stock %>%
  mutate(
    prob_sum = p_low + p_moderate + p_high + p_very_high,
    prob_sum_ok = abs(prob_sum - 1) < 1e-8,
    modal_rank_ok = modal_boot_rank %in% c("Low", "Moderate", "High", "Very High"),
    n_boot_ok = n_boot == 10000
  )

write_csv(qa_boot, f_qa_boot)

##------------------------------------------------------------------------------
## Step 4 - QA check leave-one-out completeness
##
## Workflow:
## - Check for duplicated stock x attribute rows
## - Check for duplicated stock x factor rows
## - Check recalculated ranks are legal
## - Summarize counts by stock

qa_loo_sens_dup <- loo_sens_long %>%
  count(stock_name, attribute_name) %>%
  mutate(duplicate_row = n > 1)

qa_loo_exp_dup <- loo_exp_long %>%
  count(stock_name, exposure_factor) %>%
  mutate(duplicate_row = n > 1)

qa_loo <- bind_rows(
  tibble(
    check_name = "duplicate_stock_attribute_rows",
    n_problem = sum(qa_loo_sens_dup$duplicate_row, na.rm = TRUE)
  ),
  tibble(
    check_name = "duplicate_stock_factor_rows",
    n_problem = sum(qa_loo_exp_dup$duplicate_row, na.rm = TRUE)
  ),
  tibble(
    check_name = "invalid_loo_sensitivity_rank",
    n_problem = sum(!loo_sens_long$loo_sensitivity_rank %in%
                      c("Low", "Moderate", "High", "Very High"), na.rm = TRUE)
  ),
  tibble(
    check_name = "invalid_loo_exposure_rank",
    n_problem = sum(!loo_exp_long$loo_exposure_rank %in%
                      c("Low", "Moderate", "High", "Very High"), na.rm = TRUE)
  ),
  tibble(
    check_name = "invalid_loo_vulnerability_rank_from_sensitivity",
    n_problem = sum(!loo_sens_long$loo_vulnerability_rank %in%
                      c("Low", "Moderate", "High", "Very High"), na.rm = TRUE)
  ),
  tibble(
    check_name = "invalid_loo_vulnerability_rank_from_exposure",
    n_problem = sum(!loo_exp_long$loo_vulnerability_rank %in%
                      c("Low", "Moderate", "High", "Very High"), na.rm = TRUE)
  )
)

write_csv(qa_loo, f_qa_loo)

##------------------------------------------------------------------------------
## Step 5 - Flag analytical edge cases
##
## Examples:
## - Stocks with certainty spread across three or more ranks
## - Stocks flagged as borderline
## - Stocks with unexpected pre-analysis issues
## - Stocks where multiple leave-one-out omissions increase vulnerability

qa_edge <- boot_stock %>%
  mutate(
    n_nonzero_ranks =
      (p_low > 0) + (p_moderate > 0) + (p_high > 0) + (p_very_high > 0)
  ) %>%
  filter(is_borderline | n_nonzero_ranks >= 3)

write_csv(qa_edge, f_qa_edge)

##------------------------------------------------------------------------------
## Step 6 - Make figures
##
## Figure 1. Exposure factor score distributions
##
## Structure:
## - y = exposure factor
## - x = mean score
## - horizontal boxplots
## - optional factor label can later be updated to include sample size

p_exp_box <- ggplot(
  plot_exp_scores,
  aes(x = mean_score,
      y = fct_reorder(exposure_factor, mean_score, .fun = median, na.rm = TRUE))
) +
  geom_boxplot() +
  labs(
    x = "Mean Score",
    y = "Exposure Factor"
  ) +
  theme_bw()

ggsave(filename = f_fig_exp_box, plot = p_exp_box, width = 8, height = 6, dpi = 300)

##------------------------------------------------------------------------------
## Figure 2. Exposure leave-one-out influence barplot
##
## Structure:
## - x = exposure factor
## - y = number of stocks with vulnerability rank change

p_exp_loo <- ggplot(
  loo_exp_sum %>%
    mutate(exposure_factor = fct_reorder(exposure_factor, n_rank_changed)),
  aes(x = exposure_factor, y = n_rank_changed)
) +
  geom_col() +
  coord_flip() +
  labs(
    x = NULL,
    y = "Number of Changes in Climate Vulnerability"
  ) +
  theme_bw()

ggsave(filename = f_fig_exp_loo, plot = p_exp_loo, width = 8, height = 6, dpi = 300)

##------------------------------------------------------------------------------
## Figure 3. Sensitivity attribute score distributions
##
## Structure:
## - y = sensitivity attribute
## - x = mean score
## - horizontal boxplots

p_sens_box <- ggplot(
  plot_sens_scores,
  aes(x = mean_score,
      y = fct_reorder(attribute_name, mean_score, .fun = median, na.rm = TRUE))
) +
  geom_boxplot() +
  labs(
    x = "Mean Score",
    y = "Sensitivity Attribute"
  ) +
  theme_bw()

ggsave(filename = f_fig_sens_box, plot = p_sens_box, width = 8, height = 7, dpi = 300)

##------------------------------------------------------------------------------
## Figure 4. Sensitivity leave-one-out influence barplot
##
## Structure:
## - x = attribute
## - y = number of stocks with vulnerability rank change

p_sens_loo <- ggplot(
  loo_sens_sum %>%
    mutate(attribute_name = fct_reorder(attribute_name, n_rank_changed)),
  aes(x = attribute_name, y = n_rank_changed)
) +
  geom_col() +
  coord_flip() +
  labs(
    x = NULL,
    y = "Number of Changes in Climate Vulnerability"
  ) +
  theme_bw()

ggsave(filename = f_fig_sens_loo, plot = p_sens_loo, width = 8, height = 7, dpi = 300)

##------------------------------------------------------------------------------
## Figure 5. Optional stacked barplot of vulnerability uncertainty by stock
##
## Structure:
## - one bar per stock
## - stacked proportions across Low, Moderate, High, Very High
## - order later can be refined by baseline rank and certainty

boot_stock_long <- boot_stock %>%
  select(stock_name, p_low, p_moderate, p_high, p_very_high) %>%
  pivot_longer(
    cols = starts_with("p_"),
    names_to = "rank_boot",
    values_to = "probability"
  )

p_boot_stack <- ggplot(
  boot_stock_long,
  aes(x = fct_reorder(stock_name, probability, .fun = max, na.rm = TRUE),
      y = probability,
      fill = rank_boot)
) +
  geom_col() +
  coord_flip() +
  labs(
    x = NULL,
    y = "Bootstrap Probability",
    fill = "Vulnerability Rank"
  ) +
  theme_bw()

ggsave(filename = f_fig_boot_stack, plot = p_boot_stack,
       width = 8, height = 10, dpi = 300)

##------------------------------------------------------------------------------
## Script completed

message("Script 2 completed successfully.")